### ISSUE TITLE
RTX 4080 missing (desktop)

### ISSUE THREAD

**Issue by ElPumpo** [ZenitH-AT/nvidia-data#1]
Hi I use your repo for my project. First of all thank you for your research My application has improved thanks to you.

now to the issue My users with the RTX 4080 dont have the metadata for their card. I belive for this card it should be `999`.

Thanks

**Comment by ZenitH-AT** [comment]
Hi, I updated the file. I'll need to fix the script on my PC that's supposed to run periodically to update this.

**Comment by HawaiiBeach** [comment]
Okay thanks!

**Comment by HawaiiBeach** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/issues/126
